---
- name: "Setup.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
  - name: Root shell prompt
    lineinfile:
      path: /etc/bashrc
      line: 'export PS1="\u@\[\033[01;94m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "'
      state: present

  - name: Alias vi to vim
    lineinfile:
      path: /etc/bashrc
      line: "alias vi='vim'"
      state: present

  - name: Alias ls colored
    lineinfile:
      path: /etc/bashrc
      line: "alias ls='ls --color=auto'"
      state: present

  - name: Alias ll colored
    lineinfile:
      path: /etc/bashrc
      line: "alias ll='ls -ltr --color=auto'"
      state: present

  - name: Alias la colored
    lineinfile:
      path: /etc/bashrc
      line: "alias la='ls -ltra --color=auto'
      state: present

  - name: Create vim configuration file
    file:
      path: /root/.vimrc
      state: touch
      owner: root
      group: root
      mode: 0644

  - name: Configure vim
    blockinfile:
      path: /root/.vimrc
      block: |
        set nocompatible
        set number
        set autoindent
        syntax on
        highlight Comment ctermfg=LightCyan
      marker: ""
      state: present

  - name: Disable UseDNS
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^UseDNS"
      line: "UseDNS no"
      state: present

  - name: Disable GSSAPIAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication no"
      state: present

  - name: Enable PermitRoologin
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin yes"
      state: present

  - name: Selinux permissive
    lineinfile:
      path: /etc/selinux/config
      regexp: "^SELINUX="
      line: "SELINUX=permissive"
      state: present

  - name: Update CA bundle (RedHat)
    get_url:
      url: https://curl.haxx.se/ca/cacert.pem
      dest: /etc/pki/tls/certs/ca-bundle.crt 
      force: yes
    when: ansible_os_family == "RedHat"

  - name: Install epel repo (RedHat)
    yum:
      name: "epel-release"
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Upgrade all packages (RedHat)
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install packages (RedHat)
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - ccze
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - vim
      - wget
      - sharutils
      - net-tools
      - jq
      - zip
      - unzip
      - telnet
      - bind-utils
    when: ansible_os_family == "RedHat"

  - name: Install dependencies for VirtualBox Guest Additions (RedHat)
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bzip2
      - dkms
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - perl
    when:
      - ansible_os_family == "RedHat"
      - ansible_virtualization_type == "virtualbox"

  - name: Mount VBoxGuestAdditions.iso
    mount:
      path: /mnt
      src: /home/packer/VBoxGuestAdditions.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted
    when: ansible_virtualization_type == "virtualbox"

  - name: Install VBoxGuestAdditions.iso
    command: sh /mnt/VBoxLinuxAdditions.run
    when: ansible_virtualization_type == "virtualbox"

  - name: Umount VBoxGuestAdditions.iso
    mount:
      path: /mnt
      state: absent
    when: ansible_virtualization_type == "virtualbox"

  - name: Delete VBoxGuestAdditions.iso
    file:
      path: /home/packer/VBoxGuestAdditions.iso
      state: absent
    when: ansible_virtualization_type == "virtualbox"

  - name: Install open-vm-tools (RedHat)
    yum:
      name: open-vm-tools
      state: latest
    when: 
      - ansible_os_family == "RedHat"
      - ansible_virtualization_type == "VMware"
